version: "2"
services:

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: ${OPLA_BACKEND_DATABASE_NAME}
      MYSQL_USER: ${OPLA_BACKEND_DATABASE_USER}
      MYSQL_PASSWORD: ${OPLA_BACKEND_DATABASE_PASS}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    networks: 
      - private

  backend:
    image: "opla/backend:feature_dockerfile"
    restart: always
    networks:
      private: 
        aliases:  ["${OPLA_BACKEND_DOMAIN}"]
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - PORT=80
      - OPLA_BACKEND_DATABASE_HOST
      - OPLA_BACKEND_DATABASE_NAME
      - OPLA_BACKEND_DATABASE_USER
      - OPLA_BACKEND_DATABASE_PASS

  front:
    image: "opla/front:feature_dockerfile"
    restart: always
    networks:
      - private
    depends_on:
      - backend
    expose:
      - "80"
    environment:
      - PORT=80
      - OPLA_BACKEND_DOMAIN
      - OPLA_FRONT_CLIENT_NAME
      - OPLA_BACKEND_PORT
    volumes:
      - "/srv/app/config"

  nginx:
    build: nginx
    restart: always
    depends_on:
      - front
    ports:
      - "80:80"
    networks: 
      - private
      - public
    environment:
      - OPLA_FRONT_DOMAIN
      - OPLA_BACKEND_DOMAIN
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/back.template > /etc/nginx/conf.d/back.conf && envsubst < /etc/nginx/conf.d/front.template > /etc/nginx/conf.d/front.conf && nginx -g 'daemon off;'"

networks:
  public: 
  private: 